apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: d2n8v09mc-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d2n8v09mc-dotnet-basic 
  name: d2n8v09mc-dotnet-basic
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: d2n8v09mc-dotnet-basic
    weight: 100 
